export type Semantic =
    | 'preserve'
    | 'footnote' | 'quote' | 'tech-note' | 'epigraph'
    | 'right-to-left'
    | 'code' | 'definition'
    | 'poem' | 'letter'
    | 'card' | 'address'
    | 'chapter-abstract'
    | 'character-name'
    | 'formated' | 'side-note'
    | 'editor-note' | 'extracts'
    | 'footer' | 'table-of-contents'
    | 'title-page'
    | 'illustrations'
    | 'junk'
    ;
